'use client'

import { useState, useEffect } from 'react'
import { useParams } from 'next/navigation'
import { Printer } from 'lucide-react'

type Order = {
  orderNumber: string
  customerName: string
  customerEmail: string
  customerPhone: string
  address: string
  city: string
  state: string
  subtotal: number
  deliveryFee: number
  total: number
  paymentStatus: string
  createdAt: string
  items: { id: string; quantity: number; unitPrice: number; color: string | null; product: { name: string } }[]
  payments: { reference: string; provider: string; status: string; amount: number; createdAt: string }[]
}

export default function ReceiptPage() {
  const params = useParams<{ orderNumber: string }>()
  const [order, setOrder] = useState<Order | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetch(`/api/orders/${params.orderNumber}`).then(res => res.json()).then((data) => {
      if (data.order) setOrder(data.order)
      setLoading(false)
    })
  }, [params.orderNumber])

  if (loading) return <div className="min-h-screen flex items-center justify-center text-gray-500">Loading...</div>
  if (!order) return <div className="min-h-screen flex items-center justify-center text-gray-500">Order not found.</div>

  const payment = order.payments.find((p) => p.status === 'success')

  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 print:bg-white print:py-0">
      <div className="max-w-xl mx-auto bg-white rounded-3xl shadow-sm p-8 print:shadow-none print:rounded-none">
        <div className="flex justify-between items-start mb-8">
          <div>
            <h1 className="text-2xl font-bold">TapConnect</h1>
            <p className="text-sm text-gray-500">Payment Receipt</p>
          </div>
          <button onClick={() => window.print()} className="print:hidden flex items-center gap-2 text-sm font-semibold bg-black text-white px-4 py-2 rounded-full hover:bg-gray-800">
            <Printer size={16} /> Print
          </button>
        </div>

        <div className="grid grid-cols-2 gap-4 text-sm mb-8">
          <div>
            <p className="text-gray-500">Order Number</p>
            <p className="font-semibold">#{order.orderNumber}</p>
          </div>
          <div>
            <p className="text-gray-500">Date</p>
            <p className="font-semibold">{new Date(order.createdAt).toLocaleDateString()}</p>
          </div>
          <div>
            <p className="text-gray-500">Customer</p>
            <p className="font-semibold">{order.customerName}</p>
          </div>
          <div>
            <p className="text-gray-500">Payment Status</p>
            <p className={`font-semibold capitalize ${order.paymentStatus === 'paid' ? 'text-green-600' : 'text-amber-600'}`}>{order.paymentStatus}</p>
          </div>
          {payment && (
            <>
              <div>
                <p className="text-gray-500">Payment Reference</p>
                <p className="font-mono text-xs">{payment.reference}</p>
              </div>
              <div>
                <p className="text-gray-500">Provider</p>
                <p className="font-semibold capitalize">{payment.provider}</p>
              </div>
            </>
          )}
        </div>

        <div className="border-t border-gray-100 pt-4 space-y-2 mb-4">
          {order.items.map((item) => (
            <div key={item.id} className="flex justify-between text-sm">
              <span className="text-gray-600">{item.product.name}{item.color ? ` (${item.color})` : ''} &times;{item.quantity}</span>
              <span className="font-medium">&#8358;{(item.unitPrice * item.quantity).toLocaleString()}</span>
            </div>
          ))}
        </div>

        <div className="border-t border-gray-100 pt-4 space-y-2">
          <div className="flex justify-between text-sm">
            <span className="text-gray-600">Subtotal</span>
            <span>&#8358;{order.subtotal.toLocaleString()}</span>
          </div>
          <div className="flex justify-between text-sm">
            <span className="text-gray-600">Delivery ({order.city}, {order.state})</span>
            <span>&#8358;{order.deliveryFee.toLocaleString()}</span>
          </div>
          <div className="flex justify-between font-bold text-lg pt-2 border-t border-gray-100">
            <span>Total Paid</span>
            <span>&#8358;{order.total.toLocaleString()}</span>
          </div>
        </div>

        <p className="text-xs text-gray-400 mt-8 text-center">Thank you for your order. This receipt was generated by TapConnect.</p>
      </div>
    </div>
  )
}
